### ISSUE TITLE
Broken Chocolatey Install: Unable to index into an object of type System.IO.DirectoryInfo

### ISSUE THREAD

**Issue by dahlbyk** [dahlbyk/posh-git#166]
Including this here for reference, in case anyone more in tune with Chocolatey wants to have a look:
https://github.com/ferventcoder/chocolatey-packages/issues/41

**Comment by arthg** [comment]
I am experiencing this too.  poshgit v0.5.0.2101401009.  Is there a work around?

**Comment by BenKnigge** [comment]
same error.

choco install poshgit -version 0.4.0.20120717 worked great thanks.

**Comment by dahlbyk** [comment]
Last night I pushed version 5.1 which is waiting on moderation. It was essentially a Save As... of the working 0.4 package, so fingers crossed?

**Comment by firehorseuk** [comment]
4/4/2015 - Still having the "Unable to index into an object of type System.IO.DirectoryInfo" problem

choco install poshgit -version 0.4.0.20120717 worked fine. Thanks.

**Comment by Alber70g** [comment]
This error still exists as of 20/05/2015

**Comment by dahlbyk** [comment]
0.5.1 was rejected because the package I cloned violated current best practices. The effort to fix began a month ago with #184 and I'm planning to push the rest of the way soon. Again, sorry for the inconvenience everyone... :(

**Comment by dahlbyk** [comment]
I resubmitted what I believe to be a minimal fix for the 0.5.1.20150209 package (waiting in a long approval queue), if anyone cares to give that a try: https://chocolatey.org/packages/poshgit/0.5.1.20150209.

**Comment by Alber70g** [comment]
@dahlbyk it's oke :) At least it's not a dead end which is good. Thanks a lot for the effort.

**Comment by BlueHatbRit** [comment]
@dahlbyk In response to trying 0.5.1.20150209, I'm still getting the same error at the moment which is frustrating. I'll clone to the repo and install that way for now :)

**Comment by dahlbyk** [comment]
I've updated #184 with a tentative fix that is awaiting Chocolatey moderation. I believe you can try it today with `choco install poshgit -version 0.5.2.20150825`.

**Comment by dahlbyk** [comment]
Has anyone seen this recently?

**Comment by rkeithhill** [comment]
I've done a couple of test Chocolatey installs of 0.6.1.xxxx on PS v2 and have not seen this error.
