### ISSUE TITLE
Installing from chocolatey on Powershell Version 2.0 is not making the module importable

### ISSUE THREAD

**Issue by Gilligan128** [dahlbyk/posh-git#350]
When I run powershell 2.0 as administrator and install via chocolatey, it cannot import the module. It looks like chocolatey never actually install the module into an accessible location.

**Comment by dahlbyk** [comment]
Are you getting the error I pasted in https://github.com/dahlbyk/posh-git/pull/322#issuecomment-269663743?

**Comment by Gilligan128** [comment]
Seems so, though I never tested Get-module and cannot do so atm

**Comment by dahlbyk** [comment]
@Gilligan128 try a `choco install --force poshgit` (I _believe_ that will force it to get latest)?

**Comment by rkeithhill** [comment]
Just tried this on v2 and chocolatey is not putting the pkg into any of the $env:PSModulePath dirs (bad Chocolatey). Oh well, we can fix this with this change:
![image](https://cloud.githubusercontent.com/assets/5177512/21634736/9484ef30-d216-11e6-983f-b5625e3ae3e0.png)

**Comment by dahlbyk** [comment]
Fix merged. Retry?

**Comment by Gilligan128** [comment]
Will do thank you!

**Comment by Gilligan128** [comment]
still does not seem to work for me when installing from chocolatey

**Comment by dahlbyk** [comment]
Let me clarify: are you getting an error, as I was, or are you just trying to `Import-Module posh-git` (interactively or in `$PROFILE`) and it's not finding it? The latter would be expected, though not ideal.

Assuming you mean the latter, I'm going to reopen and target 1.0 to fix this. In the meantime, you can [modify the `PSModulePath` environment variable](https://msdn.microsoft.com/en-us/library/dd878326(v=vs.85).aspx) to include the path where Chocolatey has installed posh-git, e.g. `C:\tools\poshgit\dahlbyk-posh-git-f77a781`.

**Comment by dahlbyk** [comment]
I've just pushed a preview release that might fix this. Try `choco upgrade poshgit -pre`?

**Comment by Gilligan128** [comment]
OK I will try at work today.

**Comment by dahlbyk** [comment]
0.7.0 has been released. Please reopen if this is not resolved.
